Размечает главную страницу
htmlacademy-htmlcss/995085-device-32 pull request #2
Opened 2021-09-27 14:46 UTC by tau-8

2021-09-27 17:26 UTC, Dima-Dim requested changes
Хорошо. Поправить нужно совсем чуть-чуть.

2021-09-27 17:26 UTC, Dima-Dim commented on index.html
> +      <ul class="userbar">
Это не список, потому что его элементы не однородны.

2021-09-27 17:26 UTC, Dima-Dim commented on index.html
> +        <nav class="offers-navigation">
На странице должен быть один тег nav иначе его смысл теряется.

2021-09-27 17:26 UTC, Dima-Dim commented on index.html
> +            <b>Меловые линии</b>
Пока мы не занимаемся стилизацией. Тег b тут не нужен.

2021-09-28 07:29 UTC, tau-8 commented on index.html
> +      <ul class="userbar">
Если исключить поле поиска, "Войти", "Сравнить" и "Корзина" - список?

2021-09-28 15:16 UTC, Dima-Dim commented on index.html
> +      <ul class="userbar">
Данный список состоит только из этих элементов :) если их исключить, то в списке ничего и не останется.

2021-09-28 15:32 UTC, tau-8 commented on index.html
> +      <ul class="userbar">
А верно. Перефразирую: если исключить поле поиска, но оставить "Войти", "Сравнить" и "Корзина" - это таки список? :)

2021-09-29 07:42 UTC, Dima-Dim commented on index.html
> +      <ul class="userbar">
Нет :) всё это не однородные элементы. Что их объединяет, кроме того что по макету они находятся рядом?

2021-10-01 09:19 UTC, firefoxic requested changes

2021-10-01 09:19 UTC, firefoxic commented on index.html
> +        <button class="delivery-button" type="button">
Этот элемент лучше сделать ссылкой. Без js кнопка бесполезна, а интерфейс лучше делать максимально работоспособным без js.
Сам элемент должен открывать модалку при рабочем js, а без js нужен переход на страницу с контентом модалки.

2021-10-01 09:19 UTC, firefoxic commented on index.html
> +            <p>Меловые линии</p>
В принципе не было необходимости параграф добавлять. Но можно и оставить)

2021-10-01 09:19 UTC, firefoxic commented on index.html
> +          <input class="subscription-field"  placeholder="Ваш e-mail" type="email" name="newsletter-email" required>
Не забывай про лэйблы к инпутам ;)

2021-10-01 09:19 UTC, firefoxic commented on index.html
> +          <button class="subscription-button" type="submit">Подписаться</button>
Молодец, что тип кнопки указал 👍 
Даже при том, что сабмит по умолчанию у кнопок, лучше всегда тип указывать.

2021-10-01 10:46 UTC, merged