Разметка страницы каталога
htmlacademy-htmlcss/995085-device-32 pull request #3
Opened 2021-10-01 11:11 UTC by tau-8

2021-10-01 12:47 UTC, firefoxic requested changes
Надо бы ещё поработать со ссылками на текущую страницу:
1. В навигации надо бы определиться, какая ссылка является ссылкой на текущую страницу. Сейчас вообще ничем не отличается от главной. На главной тоже надо поправить эту ссылку. Я не делал замечание по этому поводу, потому что ждал внутреннюю страницу.
2. Есть более удобный и доступный способ разметки ссылок на текущую страницу, чем удаление `href` — можно оставить все атрибуты и классы в обычном состоянии, но добавить атрибут `aria-current="page"`. И если захочешь сделать так, то надо будет все ссылки так сделать: в навигации, в хлебных крошках, в пагинации.
3. Ссылка вокруг логотипа на внутренних страницах уже не ссылка на текущую страницу ;)

2021-10-01 12:47 UTC, firefoxic commented on catalog.html
> +        <h2 class="visually-hidden">Каталог товаров с фильтрами</h2>
Кажется этот заголовок лишний. Внутри формы же есть заголовок.

2021-10-01 12:47 UTC, firefoxic commented on catalog.html
> +                  <span class="filter-checkbox-visible"></span>
Без этих спанов можно обойтись, если `input` размесить не внутри лэйбла, а перед ним. И связать лэйбл с `id` инпута через `for`.

2021-10-01 12:47 UTC, firefoxic commented on catalog.html
> +                  <input class="visually-hidden filter-checkbox-hidden" type="checkbox" name="color-white" checked>
У группы чекбоксов лучше тоже как у радиокнопок делать одинаковый `name` и разные `value`. Тогда на сервер будет отправляться вместо разрозненных данных один цельный именованный массив, содержащий только отмеченные чекбоксы из группы.

2021-10-01 15:17 UTC, tau-8 commented on catalog.html
> +                  <span class="filter-checkbox-visible"></span>
Тут такой момент: чтобы не идти против правил, задавая всем чекбоксам (и радиокнопкам) одинаковый ID, мне нужно имитировать скрипт и присвоить уникальный каждому чекбоксу и радиокнопке. Правильно понимаю?

2021-10-02 09:41 UTC, firefoxic commented on catalog.html
> +                  <span class="filter-checkbox-visible"></span>
Каждый `id` вообще в любом случае на странице всегда должен быть уникальный. Ну и как следствие этого, у каждого `input` должен быть свой уникальный `id`. Так что, хоть я и не очень понял про имитацию скрипта, но понимаешь правильно)

2021-10-02 10:18 UTC, firefoxic requested changes

2021-10-02 10:18 UTC, firefoxic commented on catalog.html
> +                    <!-- Класс, общий для всех неактивных ссылок (поможет стилизовать состояния и курсор) -->
Что это ссылка на текущую страницу достаточно селектора `[aria-current="page"]`. А курсор и нет необходимости менять ;)

2021-10-02 10:18 UTC, firefoxic commented on catalog.html
> +      <a class="footer-logo">
Забыли про эту ссылку. Как и в шапке тут надо вернуть `href`. Да и на главной надо этим ссылкам вернуть его. Раз уж таки решил на перейти на `aria-current="page"` с удаления `href`, то надо бы последовательно это сделать со всеми ссылками.

2021-10-02 10:18 UTC, firefoxic commented on catalog.html
> +              <!-- Тот же дополнительный класс, что и у breadcrumbs-link -->
Сомневаюсь, то там будут какие-то общие стили. Ну кроме совсем уж общих, вроде шрифтовых стилей, которые и так наследуются.

2021-10-02 19:14 UTC, merged